# Generated by Django 3.0.6 on 2020-05-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
    ]
