# Generated by Django 3.0.6 on 2020-05-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.CharField(max_length=200)),
                ('intro', models.CharField(default='', max_length=50)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
                ('skills', models.ManyToManyField(to='home.Skill')),
            ],
            options={
                'verbose_name_plural': 'Introduction',
            },
        ),
    ]
